apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol-data-druid-test-zookeeper-1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-druid-test-zookeeper-1
    namespace: default
  hostPath:
    path: /data1/pv/vol-data-druid-test-zookeeper-1
    type: ""
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
status:
  phase: Bound

