apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol-data-druid-on-ceph-postgresql-0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-druid-on-ceph-postgresql-0
    namespace: druid-on-ceph
  hostPath:
    path: /data1/pv/vol-data-druid-on-ceph-postgresql-0
    type: ""
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
status:
  phase: Bound

